/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.tema;

import DAOs.TemaDAO;

import entidades.Tema;
import excepcionesPropias.ExcepcionPropia;
import grafoNoDirigido.Vertice;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import listasPropias.ListaTemas;
import relacionTemas.GrafoTemas;
import vistas.principal.GUIPrincipal;

/**
 *
 * @author Alexander
 */
public class GUIRegistroTema extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIEstudiantes
     */
    
    GrafoTemas miGrafoBusqueda;
    
    TemaDAO temaDAO = new TemaDAO();
    
    public GUIRegistroTema() {
        initComponents();
        crearGrafo();
        cargarCodigo();
    }

    public void crearGrafo(){
        
        /*Creamos los vertices*/
        ListaTemas temas = null;
        try {

            temas = temaDAO.obtenerTodosTemas();
            ArrayList<Vertice> vertices = new ArrayList<>();

            for(int i = 0; i < temas.tamanio(); i++)
            {
                vertices.add(new Vertice(temas.obtenerTema(i).getDescripcion()));	
            }

            miGrafoBusqueda = new GrafoTemas(vertices);


        } catch (Exception ex) {
            Logger.getLogger(GUIConfiguracionBusqueda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        GrafoTemas grafoDeserializado = miGrafoBusqueda.deserializarGrafo();
        
        if(grafoDeserializado == null){
            miGrafoBusqueda.serializarGrafo(miGrafoBusqueda);
        } else{
            miGrafoBusqueda = grafoDeserializado;
        }
    }
    
    private void limpiar(){
        lblCodigo.setText("");
        txtDescripcion.setText("");
    }
    
    private void establecerPorDefecto(){
        cargarCodigo();
        limpiar();
    }
    
    private void cargarCodigo(){
        try {
            lblCodigo.setText(temaDAO.generarNuevoCodigo()+ "");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Hubo un error al generar código");
        }
    }
    
    public void irAGUIMateria(){
        GUIPrincipal.vacearDktpPane();
        
        GUITema guiMateria = new GUITema();
        GUIPrincipal.agregarJframe(guiMateria);
        guiMateria.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneEstudiante = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(910, 530));

        jPaneEstudiante.setPreferredSize(new java.awt.Dimension(900, 530));
        jPaneEstudiante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCodigo.setBackground(new java.awt.Color(204, 204, 204));
        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCodigo.setOpaque(true);
        jPaneEstudiante.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 250, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Registro de tema");
        jPaneEstudiante.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 370, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Descripción:");
        jPaneEstudiante.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Código:");
        jPaneEstudiante.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 80, -1));
        jPaneEstudiante.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 250, -1));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        jPaneEstudiante.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 120, 50));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        jPaneEstudiante.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 120, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        // TODO add your handling code here:
        try {
            if(txtDescripcion.getText().equals(null) || txtDescripcion.getText().equals("")){
                throw new ExcepcionPropia("Falta completar datos en el campo Descripción.");
            }
            
            Tema objMateria = new Tema();

            objMateria.setDescripcion(txtDescripcion.getText().trim());

            temaDAO.registrar(objMateria);
            
            miGrafoBusqueda.crearVertice(objMateria.getDescripcion());
            miGrafoBusqueda.serializarGrafo(miGrafoBusqueda);
            
            JOptionPane.showMessageDialog(this, String.format("Nueva materia %s registrada exitosamente", objMateria.getDescripcion()));
            irAGUIMateria();
            
            establecerPorDefecto();
        } catch (ExcepcionPropia | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        irAGUIMateria();
    }//GEN-LAST:event_btnRegresarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPaneEstudiante;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
