/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.tema;

import DAOs.TemaDAO;
import entidades.Tema;
import excepcionesPropias.ExcepcionPropia;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import listasPropias.ListaTemas;
import vistas.principal.GUIPrincipal;

/**
 *
 * @author Alexander
 */
public class GUITema extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIEstudiantes
     */
    
    TemaDAO temaDAO = new TemaDAO();
    ListaTemas listaTemas;
    
    public GUITema() {
        initComponents();
        configurarEncabezadoJTable();
        llenarJTableMaterias();
    }

    private void limpiar(){
        txtBusquedaEstudiante.setText("");
        lblCodigo.setText("");
        txtDescripcion.setText("");
    }
    
    private void establecerPorDefecto(){
        limpiar();
        llenarJTableMaterias();
    }
    
    private void configurarEncabezadoJTable(){
        jTableMaterias.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 14));
        jTableMaterias.getTableHeader().setOpaque(false);
        jTableMaterias.getTableHeader().setForeground(Color.BLACK);
        
    }
    private void llenarJTableMaterias(){
        DefaultTableModel dtm = new DefaultTableModel();
        
        try {
            listaTemas =temaDAO.obtenerTodosTemas();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Hubo un problema al cargar los datos de temas.");
        }
        
        String[] cabecera = {"Código", "Descripción de tema"}; 
        dtm.setColumnIdentifiers(cabecera);
        dtm.setColumnCount(cabecera.length);
        Object[] dataCliente = new Object[dtm.getColumnCount()];
        
        for (int i = 0; i < listaTemas.tamanio(); i++) {
            dataCliente[0] = listaTemas.obtenerTema(i).getId();
            dataCliente[1] = listaTemas.obtenerTema(i).getDescripcion();
            dtm.addRow(dataCliente);
        }
        jTableMaterias.setModel(dtm);
    }
    
    private void llenarJTableMaterias(ListaTemas temas){
        
        DefaultTableModel dtm = new DefaultTableModel();
        
        String[] cabecera = {"Código", "Descripción de tema"}; 
        dtm.setColumnIdentifiers(cabecera);
        dtm.setColumnCount(cabecera.length);
        Object[] dataCliente = new Object[dtm.getColumnCount()];
        
        for (int i = 0; i < temas.tamanio(); i++) {
            dataCliente[0] = temas.obtenerTema(i).getId();
            dataCliente[1] = temas.obtenerTema(i).getDescripcion();
            dtm.addRow(dataCliente);
        }
        jTableMaterias.setModel(dtm);
    }
    
    public void irAGUIRegistrarMateria(){
        GUIPrincipal.vacearDktpPane();
        
        GUIRegistroTema guiRegistroMateria = new GUIRegistroTema();
        GUIPrincipal.agregarJframe(guiRegistroMateria);
        guiRegistroMateria.setVisible(true);
    }
    
    public void irAGUIConfiguracionBusqueda(){
        GUIPrincipal.vacearDktpPane();
        
        GUIConfiguracionBusqueda gui = new GUIConfiguracionBusqueda();
        GUIPrincipal.agregarJframe(gui);
        gui.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpOrdenamiento = new javax.swing.ButtonGroup();
        jPaneEstudiante = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        txtBusquedaEstudiante = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableMaterias = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        lblCodigo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnNuevaMateria = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnConfiguracionTemas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(900, 530));

        jPaneEstudiante.setPreferredSize(new java.awt.Dimension(900, 530));
        jPaneEstudiante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        jLabel31.setText("Buscar");
        jPaneEstudiante.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        txtBusquedaEstudiante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaEstudianteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaEstudianteKeyReleased(evt);
            }
        });
        jPaneEstudiante.add(txtBusquedaEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 420, -1));

        jTableMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMateriasMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableMaterias);

        jPaneEstudiante.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 92, 600, 370));

        lblCodigo.setBackground(new java.awt.Color(204, 204, 204));
        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCodigo.setOpaque(true);
        jPaneEstudiante.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 250, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Temas");
        jPaneEstudiante.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Descripción");
        jPaneEstudiante.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Código");
        jPaneEstudiante.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        jPaneEstudiante.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 250, -1));

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        jPaneEstudiante.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 100, 40));

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        jPaneEstudiante.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, 40));

        btnNuevaMateria.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnNuevaMateria.setText("Nuevo tema");
        btnNuevaMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevaMateriaMouseClicked(evt);
            }
        });
        btnNuevaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaMateriaActionPerformed(evt);
            }
        });
        jPaneEstudiante.add(btnNuevaMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 150, 60));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Código");
        jPaneEstudiante.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        btnConfiguracionTemas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnConfiguracionTemas.setText("Configuación de búsquedas");
        btnConfiguracionTemas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfiguracionTemasMouseClicked(evt);
            }
        });
        jPaneEstudiante.add(btnConfiguracionTemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 250, 60));

        jLabel1.setText("por el estudiante.");
        jPaneEstudiante.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 250, 20));

        jLabel4.setText("Esta opción permite relacionar temas para");
        jPaneEstudiante.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 250, 20));

        jLabel7.setText("lograr una optimización en la búsqueda de ");
        jPaneEstudiante.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 250, 20));

        jLabel8.setText("libros relacionados según el tema consultado");
        jPaneEstudiante.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 250, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaEstudianteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaEstudianteKeyReleased
        
    }//GEN-LAST:event_txtBusquedaEstudianteKeyReleased

    private void jTableMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMateriasMouseClicked
        int filaSeleccionada = 0;
        
        if(jTableMaterias.getSelectedRow() != -1){
            filaSeleccionada = jTableMaterias.getSelectedRow();
            lblCodigo.setText(jTableMaterias.getValueAt(filaSeleccionada, 0) + "");
            txtDescripcion.setText(jTableMaterias.getValueAt(filaSeleccionada, 1) + "");
        }
    }//GEN-LAST:event_jTableMateriasMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
        try {
            Tema objMateria = new Tema();

            objMateria.setId(Integer.parseInt(lblCodigo.getText()));
            objMateria.setDescripcion(txtDescripcion.getText().trim());
            
            /*String selectedCboItem[] = cboEstadoEstudiante.getSelectedItem().toString().split(" - ");
            objEstudiante.setEstado(Integer.parseInt(selectedCboItem[0]));*/

            temaDAO.actualizar(objMateria);

            JOptionPane.showMessageDialog(this, String.format("Datos de materia %s actualizados correctamente.", objMateria.getDescripcion()));

            establecerPorDefecto();
        } catch (ExcepcionPropia | SQLException e) {
            JOptionPane.showMessageDialog(this, "Asegúrese de seleccionar un registro de la tabla.");
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(this, "Asegúrese de seleccionar un registro de la tabla.");
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        
        int opcion = JOptionPane.showConfirmDialog(this,"¿Está seguro de que desea eliminar este registro?", "Confirmación de eliminación de materia", JOptionPane.YES_NO_OPTION);
        
        if(opcion == JOptionPane.YES_OPTION){
            
            try {
            Tema objMateria = new Tema();

            objMateria.setId(Integer.parseInt(lblCodigo.getText()));
            objMateria.setDescripcion(txtDescripcion.getText().trim());

            temaDAO.eliminar(objMateria);

            JOptionPane.showMessageDialog(this, String.format("Datos de materia %s eliminados correctamente.", objMateria.getDescripcion()));

            establecerPorDefecto();
            } catch (ExcepcionPropia | SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Asegúrese de selccionar un registro de la tabla.");
            }
        }
        
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnNuevaMateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaMateriaMouseClicked
        // TODO add your handling code here:
        irAGUIRegistrarMateria();
    }//GEN-LAST:event_btnNuevaMateriaMouseClicked

    private void btnNuevaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaMateriaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnNuevaMateriaActionPerformed

    private void txtBusquedaEstudianteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaEstudianteKeyPressed
        // TODO add your handling code here:
        if(!(txtBusquedaEstudiante.getText().equals(""))){
            try {
                llenarJTableMaterias(temaDAO.obtenerTemasXDescripcion(txtBusquedaEstudiante.getText().trim()));
            } catch (SQLException ex) {
            
            }
        }
    }//GEN-LAST:event_txtBusquedaEstudianteKeyPressed

    private void btnConfiguracionTemasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfiguracionTemasMouseClicked
        // TODO add your handling code here:
        irAGUIConfiguracionBusqueda();
    }//GEN-LAST:event_btnConfiguracionTemasMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfiguracionTemas;
    private javax.swing.JButton btnEliminar;
    private javax.swing.ButtonGroup btnGrpOrdenamiento;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevaMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPaneEstudiante;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableMaterias;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTextField txtBusquedaEstudiante;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
