/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.estudiantes;

import DAOs.EstudianteDAO;
import DAOs.TemaDAO;
import entidades.Estudiante;

import entidades.Tema;
import excepcionesPropias.ExcepcionPropia;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import vistas.principal.GUIPrincipal;

/**
 *
 * @author Alexander
 */
public class GUIRegistroEstudiante extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIEstudiantes
     */
    
    EstudianteDAO estudianteDAO = new EstudianteDAO();
    
    public GUIRegistroEstudiante() {
        initComponents();
        cargarCodigo();
    }

    private void limpiar(){
        lblCodigo.setText("");
        txtNombres.setText("");
        txtApaterno.setText("");
        txtAmaterno.setText("");
    }
    
    private void establecerPorDefecto(){
        cargarCodigo();
        limpiar();
    }
    
    private void cargarCodigo(){
        try {
            lblCodigo.setText(estudianteDAO.generarNuevoCodigo()+ "");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Hubo un error al generar código");
        }
    }
    
    public void irAGUIEstudiante(){
        GUIPrincipal.vacearDktpPane();
        
        GUIEstudiantes guiEstudiante = new GUIEstudiantes();
        GUIPrincipal.agregarJframe(guiEstudiante);
        guiEstudiante.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneEstudiante = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtApaterno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAmaterno = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(910, 530));

        jPaneEstudiante.setPreferredSize(new java.awt.Dimension(900, 530));
        jPaneEstudiante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCodigo.setBackground(new java.awt.Color(204, 204, 204));
        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCodigo.setOpaque(true);
        jPaneEstudiante.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 250, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Registro de estudiante");
        jPaneEstudiante.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 430, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Código:");
        jPaneEstudiante.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 80, -1));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        jPaneEstudiante.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 120, 50));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        jPaneEstudiante.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 120, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Nombres:");
        jPaneEstudiante.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 90, -1));
        jPaneEstudiante.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 250, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Apellido paterno:");
        jPaneEstudiante.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 130, -1));
        jPaneEstudiante.add(txtApaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 250, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Apellido materno:");
        jPaneEstudiante.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 130, -1));
        jPaneEstudiante.add(txtAmaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 250, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        // TODO add your handling code here:
        try {
            if(txtNombres.getText().equals("") || txtApaterno.getText().equals("") || txtAmaterno.getText().equals("")){
                throw new ExcepcionPropia("Debe completar todos los campos");
            }
            
            Estudiante objEstudiante = new Estudiante();

            objEstudiante.setNombres(txtNombres.getText().trim());
            objEstudiante.setApellidoPaterno(txtApaterno.getText().trim());
            objEstudiante.setApellidoMaterno(txtAmaterno.getText().trim());

            estudianteDAO.registrar(objEstudiante);
            
            JOptionPane.showMessageDialog(this, String.format("Nuevo estudiante %s registrado exitosamente", objEstudiante.getNombres()));
            irAGUIEstudiante();
            
            establecerPorDefecto();
        } catch (ExcepcionPropia | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        irAGUIEstudiante();
    }//GEN-LAST:event_btnRegresarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPaneEstudiante;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTextField txtAmaterno;
    private javax.swing.JTextField txtApaterno;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
