/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.principal;

import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import vistas.estudiantes.GUIEstudiantes;
import vistas.libro.GUIAgregarNuevoEjemplar;
import vistas.libro.GUILibro;
import vistas.tema.GUITema;
import vistas.prestamo.GUIPrestamo;

/**
 *
 * @author Alexander
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public static void vacearDktpPane(){
        dktpPane.removeAll();
    }
    
    public static void agregarJframe(JInternalFrame internalFrame){
        dktpPane.add(internalFrame);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dktpPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuOptEstudiante = new javax.swing.JMenu();
        menuOptMateria = new javax.swing.JMenu();
        menuOptLibros = new javax.swing.JMenu();
        menuOptPrestamos = new javax.swing.JMenu();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout dktpPaneLayout = new javax.swing.GroupLayout(dktpPane);
        dktpPane.setLayout(dktpPaneLayout);
        dktpPaneLayout.setHorizontalGroup(
            dktpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        dktpPaneLayout.setVerticalGroup(
            dktpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        jPanel2.add(dktpPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 920, 540));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 920, 600));

        menuOptEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estudiante.png"))); // NOI18N
        menuOptEstudiante.setText("Estudiantes");
        menuOptEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuOptEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuOptEstudianteMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuOptEstudiante);

        menuOptMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/materia.png"))); // NOI18N
        menuOptMateria.setText("Temas/Tópicos");
        menuOptMateria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuOptMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuOptMateriaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuOptMateria);

        menuOptLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/libro.png"))); // NOI18N
        menuOptLibros.setText("Libros");
        menuOptLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuOptLibrosMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuOptLibros);

        menuOptPrestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prestamo.png"))); // NOI18N
        menuOptPrestamos.setText("Prestamos");
        menuOptPrestamos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuOptPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuOptPrestamosMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuOptPrestamos);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuOptMateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOptMateriaMouseClicked
        this.dktpPane.removeAll();
        GUITema guiMateria = new GUITema();
        dktpPane.add(guiMateria);
        guiMateria.setVisible(true);
    }//GEN-LAST:event_menuOptMateriaMouseClicked

    private void menuOptPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOptPrestamosMouseClicked
      // TODO add your handling code here:
        this.dktpPane.removeAll();
        GUIPrestamo guiPrestamo = new GUIPrestamo();
        dktpPane.add(guiPrestamo);
        guiPrestamo.setVisible(true);  
    }//GEN-LAST:event_menuOptPrestamosMouseClicked

    private void menuOptEstudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOptEstudianteMouseClicked
        // TODO add your handling code here:
        this.dktpPane.removeAll();
        GUIEstudiantes guiEstudiantes = new GUIEstudiantes();
        dktpPane.add(guiEstudiantes);
        guiEstudiantes.setVisible(true);
    }//GEN-LAST:event_menuOptEstudianteMouseClicked

    private void menuOptLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOptLibrosMouseClicked
        // TODO add your handling code here:
        this.dktpPane.removeAll();
        GUILibro guiLibro = new GUILibro();
        dktpPane.add(guiLibro);
        guiLibro.setVisible(true);
    }//GEN-LAST:event_menuOptLibrosMouseClicked

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JDesktopPane dktpPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu menuOptEstudiante;
    private javax.swing.JMenu menuOptLibros;
    private javax.swing.JMenu menuOptMateria;
    private javax.swing.JMenu menuOptPrestamos;
    // End of variables declaration//GEN-END:variables
}
