/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.consulta;

import DAOs.LibroDAO;
import DAOs.TemaDAO;
import entidades.Libro;
import entidades.Tema;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import listasPropias.ListaTemas;

/**
 *
 * @author Alexander
 */
public class GUIBusquedaLibros extends javax.swing.JFrame {

    /**
     * Creates new form GUIBusquedaLibros
     */
    
    LibroDAO libroDAO = new LibroDAO();
    TemaDAO temaDAO = new TemaDAO();
    ListaTemas listaTemas;
    
    public GUIBusquedaLibros() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarCboTemas();
    }

    public void cargarCboTemas(){
        try {
            listaTemas = temaDAO.obtenerTodosTemas();
            
            for (int i = 0; i < listaTemas.tamanio(); i++) {
                cboTemas.addItem(listaTemas.obtenerTema(i).getId()+ " - " + listaTemas.obtenerTema(i).getDescripcion());
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
    private void llenarJTableLibrosConsultados(ArrayList<Libro> libros){
        
        DefaultTableModel dtm = new DefaultTableModel();
        
        String[] cabecera = {"Código", "Título", "Autor", "Tema"}; 
        dtm.setColumnIdentifiers(cabecera);
        dtm.setColumnCount(cabecera.length);
        Object[] dataTema = new Object[dtm.getColumnCount()];
        
        for (int i = 0; i < libros.size(); i++) {
            dataTema[0] = libros.get(i).getId();
            dataTema[1] = libros.get(i).getTitulo();
            dataTema[2] = libros.get(i).getAutores();
            dataTema[3] = libros.get(i).getDescripcion_materia();
            dtm.addRow(dataTema);
        }
        
        jTableLibrosConsultados.setModel(dtm);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboTemas = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAnio2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPalabraClave = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAnio1 = new javax.swing.JTextField();
        btnVerDetalle = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableLibrosConsultados = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Consulta de libros");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("y");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 20, -1));

        cboTemas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTemasItemStateChanged(evt);
            }
        });
        jPanel1.add(cboTemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 330, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Seleccionar un tema:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Palabra clave:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 140, -1));
        jPanel1.add(txtAnio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 130, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Entre");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 40, -1));
        jPanel1.add(txtPalabraClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 330, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Año de publicación:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 140, -1));
        jPanel1.add(txtAnio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 130, -1));

        btnVerDetalle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVerDetalle.setText("Ver detalles");
        btnVerDetalle.setEnabled(false);
        btnVerDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerDetalleMouseClicked(evt);
            }
        });
        jPanel1.add(btnVerDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 150, 50));

        jTableLibrosConsultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableLibrosConsultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLibrosConsultadosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableLibrosConsultados);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 900, 200));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOpaque(true);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 900, 6));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Resultados");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 100, -1));

        btnConsultar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarMouseClicked(evt);
            }
        });
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 190, 70));

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 150, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboTemasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTemasItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTemasItemStateChanged

    private void jTableLibrosConsultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLibrosConsultadosMouseClicked
        int filaSeleccionada = 0;
        
        if(jTableLibrosConsultados.getSelectedRow() != -1){
            filaSeleccionada = jTableLibrosConsultados.getSelectedRow();
            
            btnVerDetalle.setEnabled(true);
            
        }
    }//GEN-LAST:event_jTableLibrosConsultadosMouseClicked

    private void btnConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseClicked
        // TODO add your handling code here:
        try {
            if(!txtAnio1.equals("") && !txtAnio2.equals("")){
                btnVerDetalle.setEnabled(false);
                int idMateria = Integer.parseInt(cboTemas.getSelectedItem().toString().split(" - ")[0]);
                int anio1 = Integer.parseInt(txtAnio1.getText());
                int anio2 = Integer.parseInt(txtAnio2.getText());
                String palabraClave = txtPalabraClave.getText();
                
                ArrayList<Libro> librosConsultados = libroDAO.consultarLibros(idMateria, anio1, anio2, palabraClave);
                llenarJTableLibrosConsultados(librosConsultados);
            }
            
        } catch (SQLException e) {
           JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (Exception e2) {
            JOptionPane.showMessageDialog(this, "Asegúrese de completar correctamente los campos.");
        }
    }//GEN-LAST:event_btnConsultarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnVerDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerDetalleMouseClicked
        // TODO add your handling code here:
        
        int filaSeleccionada = 0;
        
        if(jTableLibrosConsultados.getSelectedRow() != -1){
            
            try {
                filaSeleccionada = jTableLibrosConsultados.getSelectedRow();
                
                int idLibro = Integer.parseInt(jTableLibrosConsultados.getValueAt(filaSeleccionada, 0) + "");
                Libro libroConsultado = libroDAO.obtenerLibroXID(idLibro);
                GUIDetallesYSugerencias guiDetalles = new GUIDetallesYSugerencias(libroConsultado);
                this.setVisible(false);
                guiDetalles.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(GUIBusquedaLibros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnVerDetalleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIBusquedaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIBusquedaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIBusquedaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIBusquedaLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIBusquedaLibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerDetalle;
    private javax.swing.JComboBox<String> cboTemas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableLibrosConsultados;
    private javax.swing.JTextField txtAnio1;
    private javax.swing.JTextField txtAnio2;
    private javax.swing.JTextField txtPalabraClave;
    // End of variables declaration//GEN-END:variables
}
