/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.consulta;

import DAOs.LibroDAO;
import DAOs.TemaDAO;
import entidades.Libro;
import entidades.Tema;
import grafoNoDirigido.Vertice;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import listasPropias.ListaTemas;
import relacionTemas.GrafoTemas;
import vistas.tema.GUIConfiguracionBusqueda;

/**
 *
 * @author Alexander
 */
public class GUIDetallesYSugerencias extends javax.swing.JFrame {

    /**
     * Creates new form GUIBusquedaLibros
     */
    TemaDAO temaDAO = new TemaDAO();
    LibroDAO libroDAO = new LibroDAO();
    Libro objLibro;
    GrafoTemas miGrafo;
    
    public GUIDetallesYSugerencias(Libro libroConsultado) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.objLibro = libroConsultado;
        crearGrafo();
        mostrarInfoLibro();
        mostrarLibrosSugeridos();
    }

    public void crearGrafo(){
        /*Creamos los vertices*/
        ListaTemas temas = null;
        try {

            temas = temaDAO.obtenerTodosTemas();
            ArrayList<Vertice> vertices = new ArrayList<>();

            for(int i = 0; i < temas.tamanio(); i++)
            {
                vertices.add(new Vertice(temas.obtenerTema(i).getDescripcion()));	
            }

            miGrafo = new GrafoTemas(vertices);

        } catch (SQLException ex) {
            Logger.getLogger(GUIConfiguracionBusqueda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        GrafoTemas grafoDeserializado = miGrafo.deserializarGrafo();
        
        if(grafoDeserializado == null){
            miGrafo.serializarGrafo(miGrafo);
        } else{
            miGrafo = grafoDeserializado;
        }
    }
    
    private void llenarJTableLibrosSugeridos(ArrayList<Libro> libros){
        
        DefaultTableModel dtm = new DefaultTableModel();
        
        String[] cabecera = {"Código", "Título", "Autor", "Año", "Tema"}; 
        dtm.setColumnIdentifiers(cabecera);
        dtm.setColumnCount(cabecera.length);
        Object[] dataTema = new Object[dtm.getColumnCount()];
        
        for (int i = 0; i < libros.size(); i++) {
            dataTema[0] = libros.get(i).getId();
            dataTema[1] = libros.get(i).getTitulo();
            dataTema[2] = libros.get(i).getAutores();
            dataTema[3] = libros.get(i).getAniopublicacion();
            dataTema[4] = libros.get(i).getDescripcion_materia();
            dtm.addRow(dataTema);
        }
        
        jTableLibrosSugeridos.setModel(dtm);
    }
    
    public void mostrarInfoLibro(){
        lblId.setText(objLibro.getId() + "");
        lblTitulo.setText(objLibro.getTitulo());
        lblAnio.setText(objLibro.getAniopublicacion() + "");
        lblAutor.setText(objLibro.getAutores());
        lblIsbn.setText(objLibro.getIsbn());
    }
    
    public void mostrarLibrosSugeridos(){
        try {
            
            ArrayList<String> temasRelacionados = miGrafo.obtenerTemasRelacionados(objLibro.getDescripcion_materia());
            
            ArrayList<Libro> librosSugeridos = libroDAO.obtenerLibrosRelacionados(temasRelacionados);
            
            llenarJTableLibrosSugeridos(librosSugeridos);
        } catch (SQLException ex) {
            Logger.getLogger(GUIDetallesYSugerencias.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableLibrosSugeridos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        lblIsbn = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Información de libro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("ID:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 140, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("ISBN:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 140, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Título:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 140, -1));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 150, 50));

        jTableLibrosSugeridos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableLibrosSugeridos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLibrosSugeridosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableLibrosSugeridos);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 900, 200));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOpaque(true);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 900, 6));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Libros sugeridos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 140, -1));

        lblIsbn.setBackground(new java.awt.Color(204, 204, 204));
        lblIsbn.setOpaque(true);
        jPanel1.add(lblIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 390, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Año de publicación:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 140, -1));

        lblId.setBackground(new java.awt.Color(204, 204, 204));
        lblId.setOpaque(true);
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 130, 20));

        lblTitulo.setBackground(new java.awt.Color(204, 204, 204));
        lblTitulo.setOpaque(true);
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 390, 20));

        lblAnio.setBackground(new java.awt.Color(204, 204, 204));
        lblAnio.setOpaque(true);
        jPanel1.add(lblAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 390, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Autor:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 140, -1));

        lblAutor.setBackground(new java.awt.Color(204, 204, 204));
        lblAutor.setOpaque(true);
        jPanel1.add(lblAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 390, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableLibrosSugeridosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLibrosSugeridosMouseClicked

    }//GEN-LAST:event_jTableLibrosSugeridosMouseClicked

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        
        GUIBusquedaLibros guiBusqueda =  new GUIBusquedaLibros();
        guiBusqueda.setVisible(true);
    }//GEN-LAST:event_btnRegresarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableLibrosSugeridos;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
